name 'ch-base'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ch-base'
long_description 'Installs/Configures ch-base'
version '0.1.1'
